# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=20)),
                ('work_dir', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('test_c', models.CharField(max_length=20)),
                ('prod_c', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('code',),
                'db_table': 'project',
            },
        ),
    ]
